In [1]:
import numpy as np
import pandas as pd

In [2]:
#Setting colors for plot
custom_colors =["blue", "sienna", "limegreen", "red", "black",'cyan']
#setting relative path for data
path = "./data"

In [17]:
batting_salary =pd.read_csv(path+"/battingSalaries.csv")
columns = batting_salary.columns.tolist()
cols_to_use = columns[1:len(columns)-1] 
print(columns)
print(cols_to_use)

['Player', 'I', 'R', 'B', 'Outs', 'Avg', 'SR', 'HS', '4s', '6s', '50', '100', 'Salary', 'Year']
['I', 'R', 'B', 'Outs', 'Avg', 'SR', 'HS', '4s', '6s', '50', '100', 'Salary']

In [18]:
display(batting_salary)

,Player,I,R,B,Outs,Avg,SR,HS,4s,6s,50,100,Salary,Year
0,RD Gaikwad,16,635,466,14,45.36,136.27,101,64,23,4,1,28600,2021
1,F du Plessis,16,634,458,14,45.29,138.43,95,61,23,6,0,250000,2021
2,KL Rahul,13,626,451,10,62.60,138.80,98,48,30,6,0,1718750,2021
3,S Dhawan,16,587,471,15,39.13,124.63,92,63,16,3,0,812500,2021
4,GJ Maxwell,14,513,356,12,42.75,144.10,78,48,21,6,0,2035700,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,Washington Sundar,5,65,38,3,21.67,171.05,35,5,4,0,0,500000,2018
542,WP Saha,10,122,102,8,15.25,119.61,35,17,1,0,0,781250,2018
543,YK Pathan,13,260,200,9,28.89,130.00,45,22,11,0,0,296880,2018
544,YS Chahal,1,0,4,0,0.00,0.00,0,0,0,0,0,937500,2018
545,Yuvraj Singh,6,65,73,6,10.83,89.04,20,6,2,0,0,312500,2018

In [23]:
batting_salary['Salary'] = batting_salary['Salary'].astype(int)

In [24]:
batting_salary.describe()

,I,R,B,Outs,Avg,SR,HS,4s,6s,50,100,Salary,Year
count,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.00000,546.000000,546.000000,546.000000,5.460000e+02,546.000000
mean,6.435897,134.446886,101.326007,5.047619,18.391648,110.320751,35.241758,11.71978,5.608059,0.741758,0.036630,6.262015e+05,2019.507326
std,4.963030,166.885034,119.372810,4.488673,16.520530,49.794822,31.743123,15.99106,7.805917,1.381787,0.206622,6.147735e+05,1.117394
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.500000e+04,2018.000000
25%,2.000000,9.250000,11.000000,1.000000,5.000000,87.500000,7.000000,1.00000,0.000000,0.000000,0.000000,1.562500e+05,2019.000000
50%,5.000000,58.500000,46.000000,4.000000,15.125000,119.370000,26.000000,4.00000,2.000000,0.000000,0.000000,4.375000e+05,2019.000000
75%,11.000000,218.500000,161.750000,8.000000,28.750000,139.032500,58.750000,18.00000,9.000000,1.000000,0.000000,9.375000e+05,2021.000000
max,17.000000,735.000000,518.000000,17.000000,101.000000,333.330000,130.000000,68.00000,52.000000,8.000000,2.000000,2.656250e+06,2021.000000

In [25]:
# For batting data only selecting batsmen who satisfy following criteria
# 1) Total score more than 200
# 2) Average score more than 10
# 3) Strike Rate more than 95
data=batting_salary[['Player', 'I', 'R', 'Outs', 'Avg', 'SR', 'HS', '4s', '6s', '50', '100', 'Salary']].groupby(["Player"],as_index=False).agg({'I':'sum', 'R':'sum', 'Outs':'sum', 'Avg':'mean', 'SR':'mean','HS':'mean', '4s':'sum', '6s':'sum', '50':'sum', '100':'sum', 'Salary':'mean'})
#data=data[(data['Runs'] > 200) & (data['Avg'] > 10) & (data['SR'] > 95) ]
print(len(data))
display(data)

223

,Player,I,R,Outs,Avg,SR,HS,4s,6s,50,100,Salary
0,A Dananjaya,1,4,0,0.0000,80.0000,4.00,0,0,0,0,78130.0
1,A Mishra,5,22,2,5.2500,68.7500,4.50,2,0,0,0,625000.0
2,A Nortje,3,7,1,7.0000,116.6700,3.00,0,0,0,0,28600.0
3,AB de Villiers,52,1689,39,43.5575,158.9100,80.25,126,95,18,0,1718750.0
4,AD Nath,6,70,6,10.6000,88.1250,16.50,6,2,0,0,335275.0
...,...,...,...,...,...,...,...,...,...,...,...,...
218,Y Prithvi Raj,1,0,0,0.0000,0.0000,0.00,0,0,0,0,28600.0
219,YBK Jaiswal,13,289,13,19.1150,119.5600,42.00,34,12,1,0,342900.0
220,YK Pathan,20,300,12,21.1100,109.4450,30.50,23,12,0,0,296880.0
221,YS Chahal,8,17,3,1.0000,26.9675,3.25,0,0,0,0,937500.0
222,Yuvraj Singh,10,163,10,17.6650,109.8550,36.50,13,8,1,0,227700.0

In [27]:
from sklearn.preprocessing import MinMaxScaler
#Scaling the data
scaler = MinMaxScaler(feature_range=(0,1))

In [28]:
bat_data=batting_salary.iloc[:,2:].to_numpy()

In [29]:
batting_data_normalized = scaler.fit_transform(bat_data)

In [30]:
batting_data_normalized

array([[0.86394558, 0.89941973, 0.82352941, ..., 0.5       , 0.00514908,
        1.        ],
       [0.86258503, 0.88394584, 0.82352941, ..., 0.        , 0.08897302,
        1.        ],
       [0.85170068, 0.87040619, 0.58823529, ..., 0.        , 0.64505442,
        1.        ],
       ...,
       [0.3537415 , 0.38491296, 0.52941176, ..., 0.        , 0.1067222 ,
        0.        ],
       [0.        , 0.00580271, 0.        , ..., 0.        , 0.34926645,
        0.        ],
       [0.08843537, 0.13926499, 0.35294118, ..., 0.        , 0.11263606,
        0.        ]])

### Regression Tree

In [31]:
from sklearn.tree import DecisionTreeRegressor

In [34]:
X=batting_salary.iloc[:,2:-2]

In [35]:
X

       R    B  Outs    Avg      SR   HS  4s  6s  50  100
0    635  466    14  45.36  136.27  101  64  23   4    1
1    634  458    14  45.29  138.43   95  61  23   6    0
2    626  451    10  62.60  138.80   98  48  30   6    0
3    587  471    15  39.13  124.63   92  63  16   3    0
4    513  356    12  42.75  144.10   78  48  21   6    0
..   ...  ...   ...    ...     ...  ...  ..  ..  ..  ...
541   65   38     3  21.67  171.05   35   5   4   0    0
542  122  102     8  15.25  119.61   35  17   1   0    0
543  260  200     9  28.89  130.00   45  22  11   0    0
544    0    4     0   0.00    0.00    0   0   0   0    0
545   65   73     6  10.83   89.04   20   6   2   0    0

[546 rows x 10 columns]

In [37]:
Y=batting_salary.Salary
Y

0        28600
1       250000
2      1718750
3       812500
4      2035700
        ...
541     500000
542     781250
543     296880
544     937500
545     312500
Name: Salary, Length: 546, dtype: int32

In [38]:
# Fit regression model
regr_1 = DecisionTreeRegressor(max_depth=2)
regr_2 = DecisionTreeRegressor(max_depth=5)

In [40]:
regr_1.fit(X, Y)
regr_2.fit(X, Y)

DecisionTreeRegressor(criterion='mse', max_depth=5, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=None, splitter='best')

In [41]:
y_1 = regr_1.predict(X)
y_2 = regr_2.predict(X)

In [49]:
df = pd.DataFrame({'Player':batting_salary.Player,'Actual': Y, 'Predicted': y_1})
df['Predicted'] = df['Predicted'].astype(int)
df

                Player   Actual  Predicted
0           RD Gaikwad    28600     912687
1         F du Plessis   250000     912687
2             KL Rahul  1718750    1544224
3             S Dhawan   812500     912687
4           GJ Maxwell  2035700     912687
..                 ...      ...        ...
541  Washington Sundar   500000     419738
542            WP Saha   781250     912687
543          YK Pathan   296880     912687
544          YS Chahal   937500     419738
545       Yuvraj Singh   312500     912687

[546 rows x 3 columns]

In [50]:
df1 = pd.DataFrame({'Player':batting_salary.Player,'Actual': Y, 'Predicted': y_2})
df1['Predicted'] = df1['Predicted'].astype(int)
df1

                Player   Actual  Predicted
0           RD Gaikwad    28600     724123
1         F du Plessis   250000     724123
2             KL Rahul  1718750    1975447
3             S Dhawan   812500    1142523
4           GJ Maxwell  2035700     724123
..                 ...      ...        ...
541  Washington Sundar   500000     553565
542            WP Saha   781250     808684
543          YK Pathan   296880    1142523
544          YS Chahal   937500     304920
545       Yuvraj Singh   312500     808684

[546 rows x 3 columns]