In [1]:
import numpy as np
import pandas as pd

In [2]:
#Setting colors for plot
custom_colors =["blue", "sienna", "limegreen", "red", "black",'cyan']
#setting relative path for data
path = "./data"

In [3]:
batting_salary =pd.read_csv(path+"/battingSalaries.csv")
columns = batting_salary.columns.tolist()
cols_to_use = columns[1:len(columns)-1] 
print(columns)
print(cols_to_use)

['Player', 'I', 'R', 'B', 'Outs', 'Avg', 'SR', 'HS', '4s', '6s', '50', '100', 'Salary', 'Year']
['I', 'R', 'B', 'Outs', 'Avg', 'SR', 'HS', '4s', '6s', '50', '100', 'Salary']

In [4]:
display(batting_salary)

,Player,I,R,B,Outs,Avg,SR,HS,4s,6s,50,100,Salary,Year
0,RD Gaikwad,16,635,466,14,45.36,136.27,101,64,23,4,1,28600,2021
1,F du Plessis,16,634,458,14,45.29,138.43,95,61,23,6,0,250000,2021
2,KL Rahul,13,626,451,10,62.60,138.80,98,48,30,6,0,1718750,2021
3,S Dhawan,16,587,471,15,39.13,124.63,92,63,16,3,0,812500,2021
4,GJ Maxwell,14,513,356,12,42.75,144.10,78,48,21,6,0,2035700,2021
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
541,Washington Sundar,5,65,38,3,21.67,171.05,35,5,4,0,0,500000,2018
542,WP Saha,10,122,102,8,15.25,119.61,35,17,1,0,0,781250,2018
543,YK Pathan,13,260,200,9,28.89,130.00,45,22,11,0,0,296880,2018
544,YS Chahal,1,0,4,0,0.00,0.00,0,0,0,0,0,937500,2018
545,Yuvraj Singh,6,65,73,6,10.83,89.04,20,6,2,0,0,312500,2018

In [5]:
batting_salary['Salary'] = batting_salary['Salary'].astype(int)

In [6]:
batting_salary.describe()

,I,R,B,Outs,Avg,SR,HS,4s,6s,50,100,Salary,Year
count,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.000000,546.00000,546.000000,546.000000,546.000000,5.460000e+02,546.000000
mean,6.435897,134.446886,101.326007,5.047619,18.391648,110.320751,35.241758,11.71978,5.608059,0.741758,0.036630,6.262015e+05,2019.507326
std,4.963030,166.885034,119.372810,4.488673,16.520530,49.794822,31.743123,15.99106,7.805917,1.381787,0.206622,6.147735e+05,1.117394
min,1.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.00000,0.000000,0.000000,0.000000,1.500000e+04,2018.000000
25%,2.000000,9.250000,11.000000,1.000000,5.000000,87.500000,7.000000,1.00000,0.000000,0.000000,0.000000,1.562500e+05,2019.000000
50%,5.000000,58.500000,46.000000,4.000000,15.125000,119.370000,26.000000,4.00000,2.000000,0.000000,0.000000,4.375000e+05,2019.000000
75%,11.000000,218.500000,161.750000,8.000000,28.750000,139.032500,58.750000,18.00000,9.000000,1.000000,0.000000,9.375000e+05,2021.000000
max,17.000000,735.000000,518.000000,17.000000,101.000000,333.330000,130.000000,68.00000,52.000000,8.000000,2.000000,2.656250e+06,2021.000000

In [7]:
# For batting data only selecting batsmen who satisfy following criteria
# 1) Total score more than 200
# 2) Average score more than 10
# 3) Strike Rate more than 95
data=batting_salary[['Player', 'I', 'R', 'Outs', 'Avg', 'SR', 'HS', '4s', '6s', '50', '100', 'Salary']].groupby(["Player"],as_index=False).agg({'I':'sum', 'R':'sum', 'Outs':'sum', 'Avg':'mean', 'SR':'mean','HS':'mean', '4s':'sum', '6s':'sum', '50':'sum', '100':'sum', 'Salary':'mean'})
data=data[(data['R'] > 200) & (data['Avg'] > 15) & (data['SR'] > 100) ]
print(len(data))
display(data)

67

,Player,I,R,Outs,Avg,SR,HS,4s,6s,50,100,Salary
3,AB de Villiers,52,1689,39,43.5575,158.9100,80.25,126,95,18,0,1718750.0
5,AD Russell,44,1126,36,31.1350,171.6400,61.75,71,106,6,0,1328130.0
7,AJ Finch,21,402,20,19.5400,122.6000,49.00,34,16,1,0,798675.0
10,AM Rahane,36,884,34,20.8325,115.4275,59.50,97,16,3,1,692500.0
14,AT Rayudu,57,1499,45,32.9975,130.1775,75.00,119,70,7,1,343750.0
...,...,...,...,...,...,...,...,...,...,...,...,...
212,V Shankar,33,611,25,27.2950,120.5600,43.50,33,27,2,0,500000.0
214,VR Iyer,10,370,9,41.1100,128.4700,67.00,37,14,4,0,28600.0
216,WP Saha,28,553,25,29.5850,128.8275,48.50,61,12,2,0,323862.5
219,YBK Jaiswal,13,289,13,19.1150,119.5600,42.00,34,12,1,0,342900.0
220,YK Pathan,20,300,12,21.1100,109.4450,30.50,23,12,0,0,296880.0

In [8]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
x = sc_x.fit_transform(data.iloc[:,1:-1])
y = sc_y.fit_transform(data.iloc[:,-1:])
#print(scaled_data)

In [9]:
#x

array([[ 1.02141829,  1.37384775,  0.64386582,  1.49333295,  1.9003158 ,
         0.89502706,  0.77448867,  2.22202442,  2.48480981, -0.49930891],
       [ 0.46560082,  0.32448234,  0.414403  ,  0.03546404,  2.87497756,
        -0.07436291, -0.25175756,  2.66763857,  0.02750712, -0.49930891],
       [-1.13237439, -1.02496804, -0.8093987 , -1.32529185, -0.87972887,
        -0.742456  , -0.94214138, -0.97829538, -0.996369  , -0.49930891],
       [-0.09021664, -0.12657704,  0.26142779, -1.17360776, -1.42888531,
        -0.19226169,  0.23337703, -0.97829538, -0.58681855,  1.26141199],
       [ 1.3688042 ,  1.01971022,  1.10279146,  0.25404169, -0.29956394,
         0.61992991,  0.64387552,  1.20926499,  0.23228234,  1.26141199],
       [-1.41028312, -1.36046675, -1.26832434, -1.59227931,  1.15534651,
        -1.71184597, -1.35263987, -1.05931613, -1.20114423, -0.49930891],
       [-1.20185157, -1.325053  , -1.26832434, -0.74232032,  0.22987723,
        -1.80354503, -1.25934476, -1.14033689, -1.20114423, -0.49930891],
       [-0.50707974, -0.01288026, -0.12101024,  0.79730739,  0.19472152,
         0.27060019,  0.30801312,  0.11548481,  0.23228234, -0.49930891],
       [ 0.25716927,  0.72148915,  0.49089061,  0.61520825,  0.49268371,
         1.2487234 ,  0.49460334,  2.10049329,  0.84660802,  1.26141199],
       [-0.57655692, -0.12657704, -0.19749785,  0.08710118, -0.69214668,
         1.27492313,  0.19605898, -0.73523311,  0.02750712,  1.26141199],
       [-1.13237439, -1.01378475, -1.19183674, -0.17401843, -1.24723684,
        -0.742456  , -0.96080041, -1.14033689, -0.79159378, -0.49930891],
       [-0.09021664,  0.90042179,  0.10845258,  1.57342919, -0.4091145 ,
         0.91686017,  0.73717063,  0.03446405,  1.66570891,  1.26141199],
       [-0.99342002, -1.26168102, -1.42129956, -0.63317819,  2.25059683,
        -1.67254638, -1.25934476, -0.937785  , -0.996369  , -0.49930891],
       [-0.43760256, -1.00632922, -0.7329111 ,  0.76542537, -1.0533381 ,
        -0.97825356, -1.18470867, -0.89727462, -0.79159378, -0.49930891],
       [-1.13237439, -0.69133321, -0.7329111 , -0.66183289, -0.234293  ,
        -0.60272411, -0.56896094, -0.28961897, -0.58681855, -0.49930891],
       [-0.57655692, -0.74724966, -0.65642349, -0.51552767, -1.30504278,
        -0.29706061, -0.83018725, -0.4111501 , -0.996369  , -0.49930891],
       [ 0.67403237,  1.28438143,  0.79684104,  0.91476231, -0.15772884,
         1.20942381,  1.33425935,  0.72314046,  1.66570891, -0.49930891],
       [-0.02073946, -0.30178193,  0.03196497, -0.79170811, -0.39431209,
        -0.56779114, -0.25175756, -0.4111501 ,  0.02750712, -0.49930891],
       [ 1.02141829,  0.22010496,  0.3379154 , -0.0158797 ,  1.54601514,
        -0.1529621 , -0.21443951,  1.20926499, -0.58681855, -0.49930891],
       [ 0.25716927,  0.33752951,  0.414403  ,  0.01551333, -0.11963817,
         0.26623356,  0.0467868 ,  0.8446716 ,  0.43705757, -0.49930891],
       [ 0.18769209,  0.91160508,  0.3379154 ,  1.15710478,  1.30330675,
         1.64171934,  1.11035108,  0.96620273,  0.84660802,  1.26141199],
       [-1.8966234 , -1.27100043, -1.65076238, -0.0977363 , -0.63357509,
         0.64612963, -1.01677747, -1.30237839, -0.79159378, -0.49930891],
       [-0.6460341 ,  0.16046074, -0.42696067,  1.40091421,  0.60025635,
         1.47578772,  0.27069507,  0.23701594,  0.23228234,  1.26141199],
       [ 0.53507801, -0.05015789, -0.19749785,  0.4333047 ,  1.78566097,
         0.35793262, -0.55030191,  1.08773386, -0.38204333, -0.49930891],
       [ 1.3688042 ,  0.35616833,  0.72035343, -0.16228272,  0.28615188,
        -0.07436291,  0.53192138,  0.03446405, -0.1772681 , -0.49930891],
       [ 0.88246392, -0.53849491,  0.49089061, -1.50866236, -0.65845845,
        -1.26645058, -0.47566582, -0.57319161, -1.20114423, -0.49930891],
       [ 1.22984984,  2.9711944 ,  1.10279146,  3.04450078,  0.48234754,
         2.23121324,  2.5470958 ,  2.82968008,  3.50868593,  3.0221329 ],
       [ 0.67403237,  0.96565765,  0.26142779,  1.18585728, -0.53959259,
         0.44963167,  0.84912476,  0.19650556,  1.46093369, -0.49930891],
       [ 0.67403237,  0.67861987,  1.10279146, -0.21274628,  0.56886505,
         0.51513099,  0.68119356,  0.4800782 ,  0.43705757,  1.26141199],
       [ 0.67403237,  0.73267244,  0.56737822,  0.78772322, -0.74172197,
         0.58063031,  0.51326236, -0.0465567 ,  1.25615846, -0.49930891],
       [-0.36812537, -0.53290326, -0.12101024, -1.38132988,  0.16747743,
        -0.69005654, -0.60627898,  0.07497443, -0.38204333, -0.49930891],
       [ 0.25716927, -0.37447331, -0.35047306,  0.04573279,  0.02468528,
        -1.12235207, -0.41968876, -0.37063972, -0.58681855, -0.49930891],
       [ 0.88246392,  0.43445136, -0.35047306,  2.25879481, -0.54074105,
        -0.32326034, -0.19578049,  0.92569235,  0.02750712, -0.49930891],
       [-0.29864819, -0.72674696, -0.7329111 , -0.59298338, -0.70765092,
        -1.20095126, -0.86750529, -0.85676425, -0.996369  , -0.49930891],
       [-0.50707974, -0.64473617, -0.27398546, -0.83982453,  0.92616446,
        -0.56779114, -0.90482334,  0.15599518, -0.79159378, -0.49930891],
       [ 1.29932702,  0.80349994,  1.4852295 , -0.32130163,  0.030619  ,
         0.76402842,  0.84912476,  0.96620273,  0.64183279, -0.49930891],
       [-1.20185157, -0.7938467 , -0.88588631, -0.25968914,  0.43526059,
        -0.16606196, -0.30773462, -1.05931613, -0.58681855, -0.49930891],
       [-1.54923748, -1.32878076, -1.57427477, -0.57537981,  0.99379614,
        -0.19226169, -1.31532183, -0.97829538, -0.79159378, -0.49930891],
       [ 1.09089547,  0.65811717,  1.71469232, -0.72119604,  0.88316092,
         0.77712828,  1.31560032,  0.19650556,  0.84660802, -0.49930891],
       [ 0.9519411 ,  1.07749056,  1.25576668,  0.07888618, -0.43757084,
         0.38413235,  1.03571499,  0.88518197,  1.05138324, -0.49930891],
       [-0.99342002, -1.14239259, -0.8093987 , -1.43130445, -1.31563416,
        -1.26645058, -1.03543649, -1.14033689, -0.996369  , -0.49930891],
       [-0.43760256, -0.86840197, -0.8093987 , -0.66486462, -1.09334288,
        -1.58084733, -0.99811845, -0.61370198, -0.996369  , -0.49930891],
       [ 0.11821491, -0.55526984, -1.11534913,  1.52179205,  0.41573672,
        -1.08305248, -0.624938  , -0.49217085, -0.79159378, -0.49930891],
       [ 0.60455519,  0.07844995,  0.64386582, -0.68540211, -0.27161803,
         0.42343194,  0.15874094, -0.37063972, -0.1772681 , -0.49930891],
       [-1.0628972 , -0.21045172, -0.96237392,  2.03581627, -0.42876596,
         1.22252367, -0.08382635, -0.45166047,  0.23228234,  1.26141199],
       [ 1.16037265,  0.84264146,  1.5617171 , -0.39875733, -0.37631951,
         0.67232936,  0.97973792,  0.60160933,  0.43705757, -0.49930891],
       [ 1.57723575,  1.8286349 ,  1.40874189,  0.96346552,  0.80506548,
         0.8819272 ,  1.76341686,  1.73589989,  1.25615846,  1.26141199],
       [ 0.39612364, -0.01474414,  0.79684104, -0.73293175, -0.62017637,
        -0.36255993,  0.00946876,  0.11548481, -0.58681855, -0.49930891],
       [ 1.92462167,  2.3691606 ,  2.02064274,  0.96522588,  0.10699175,
         1.75961812,  3.14418451,  0.56109896,  2.07525936,  3.0221329 ],
       [-1.0628972 , -1.03055969, -0.96237392, -1.25135686, -0.99610639,
        -1.30138355, -1.12873161, -0.73523311, -0.996369  , -0.49930891],
       [ 1.43828139,  1.45585855,  1.71469232,  0.2493474 ,  0.31180088,
         0.67232936,  2.28586949,  0.27752632,  1.25615846, -0.49930891],
       [ 0.39612364,  0.06726666,  0.49089061, -0.53586957, -0.58342557,
        -0.02633008,  0.36399018, -0.4111501 ,  0.43705757, -0.49930891],
       [-0.99342002, -1.14612035, -1.19183674, -1.0495026 ,  2.43652013,
        -0.84725492, -1.01677747, -0.89727462, -0.79159378, -0.49930891],
       [-0.6460341 , -0.81062164, -0.8093987 , -0.6575298 ,  0.94632636,
        -0.28832737, -0.94214138, -0.37063972, -0.79159378, -0.49930891],
       [ 0.39612364, -0.50121727,  0.79684104, -1.817605  ,  1.80059098,
        -0.53285817, -0.27041658,  0.19650556, -0.58681855, -0.49930891],
       [-0.43760256, -0.3148291 , -0.35047306, -0.04688154, -1.06475892,
        -0.14859548, -0.17712147, -1.01880575,  0.02750712, -0.49930891],
       [ 0.39612364,  0.55933144,  0.79684104,  0.01766488,  0.02398344,
         1.86005041,  0.64387552,  1.12824424,  0.23228234,  3.0221329 ],
       [ 1.16037265,  1.14831806,  1.17927907,  0.42538309, -1.11420661,
         0.55443058,  0.60655747,  0.64211971,  0.84660802, -0.49930891],
       [-1.96610058, -1.36792228, -1.80373759,  0.9643457 , -0.79895368,
        -0.89965438, -1.24068574, -1.42390953, -0.996369  , -0.49930891],
       [ 1.16037265,  1.28624531,  1.40874189,  0.33883221,  0.87607874,
         1.90371663,  0.73717063,  1.41181688,  0.43705757,  3.0221329 ],
       [ 1.16037265,  0.86687192,  1.10279146,  0.15722206, -0.55662811,
         0.09593533,  0.97973792, -0.16808783,  0.84660802, -0.49930891],
       [ 1.43828139,  1.70189094,  1.4852295 ,  0.85901768, -0.28654804,
         1.32732259,  1.48353152,  0.43956782,  1.25615846,  1.26141199],
       [-0.29864819, -0.63541676, -0.42696067, -0.41518733, -1.03591976,
        -1.03065302, -0.96080041, -0.53268123, -0.79159378, -0.49930891],
       [-1.8966234 , -1.08461226, -1.65076238,  1.20610138, -0.43029725,
         0.20073424, -0.88616432, -1.05931613, -0.38204333, -0.49930891],
       [-0.6460341 , -0.7435219 , -0.42696067, -0.14643951, -0.40292556,
        -0.76865573, -0.43834778, -1.14033689, -0.79159378, -0.49930891],
       [-1.68819185, -1.23558668, -1.34481195, -1.37516863, -1.11248392,
        -1.10925221, -0.94214138, -1.14033689, -0.996369  , -0.49930891],
       [-1.20185157, -1.21508398, -1.42129956, -1.14104116, -1.8869304 ,
        -1.71184597, -1.14739063, -1.14033689, -1.20114423, -0.49930891]])

In [90]:
#y

In [91]:
from sklearn.svm import SVR

In [92]:
regressor = SVR(kernel='rbf')
regressor.fit(x,y)

C:\Users\callp\AppData\Local\Continuum\anaconda3\lib\site-packages\sklearn\utils\validation.py:724: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=1.0, cache_size=200, coef0=0.0, degree=3, epsilon=0.1,
    gamma='auto_deprecated', kernel='rbf', max_iter=-1, shrinking=True,
    tol=0.001, verbose=False)

In [93]:
y_pred = sc_y.inverse_transform(regressor.predict(x))

In [94]:
player_list = ['AB de Villiers','MS Dhoni','AD Russell', 'V Kohli', 'KD Karthik','Washington Sundar','JJ Bumrah']

In [95]:
pd.set_option('display.max_rows', None)
df = pd.DataFrame({'Player':data.Player,'Actual': data.Salary, 'Predicted': y_pred})
df['Actual'] = df['Actual'].astype(int)
df['Predicted'] = df['Predicted'].astype(int)
#display(df)
display(df[df.Player.isin(player_list)])

             Player   Actual  Predicted
3    AB de Villiers  1718750    1467001
5        AD Russell  1328130    1259990
94       KD Karthik  1156250    1006176
130        MS Dhoni  2343750    1589898
211         V Kohli  2656250     943287

In [16]:
from sklearn.metrics import mean_squared_error

In [17]:
# Calculation of Mean Squared Error (MSE)
int(mean_squared_error(data.Salary,y_pred))

267901086092

In [86]:
print("Mean squared error: %.2f" % mean_squared_error(data.Salary, y_pred))

Mean squared error: 267901086092.34

In [87]:
print("Coefficient of determination: %.2f" % r2_score(data.Salary, y_pred))

Coefficient of determination: 0.42

## Decision Tree Regressoion

In [18]:
from sklearn.tree import DecisionTreeRegressor
dec_tree_regreesion = DecisionTreeRegressor(max_depth=3,random_state=20)

In [19]:
dec_tree_regreesion.fit(x,y)

DecisionTreeRegressor(criterion='mse', max_depth=3, max_features=None,
                      max_leaf_nodes=None, min_impurity_decrease=0.0,
                      min_impurity_split=None, min_samples_leaf=1,
                      min_samples_split=2, min_weight_fraction_leaf=0.0,
                      presort=False, random_state=20, splitter='best')

In [73]:
y_pred_dt = sc_y.inverse_transform(dec_tree_regreesion.predict(x))
y_pred_dt
#print(y_pred_dt.shape)

array([ 944007.31182796,  944007.31182796,  613376.43518519,
        944007.31182796,  944007.31182796,  138407.5       ,
        138407.5       ,  613376.43518519,  944007.31182796,
        613376.43518519,  312564.16666667, 2148440.        ,
        613376.43518519,  613376.43518519,  613376.43518519,
        613376.43518519,  944007.31182796,  944007.31182796,
        944007.31182796,  944007.31182796,  944007.31182796,
        138407.5       ,  613376.43518519,  944007.31182796,
        944007.31182796,  944007.31182796, 2239583.33333333,
        944007.31182796,  944007.31182796,  944007.31182796,
        613376.43518519,  944007.31182796, 2148440.        ,
        613376.43518519,  613376.43518519,  944007.31182796,
        312564.16666667, 2214300.        ,  944007.31182796,
        944007.31182796,  138407.5       ,  613376.43518519,
        944007.31182796,  944007.31182796,  613376.43518519,
        944007.31182796, 2239583.33333333,  944007.31182796,
        812500.        ,  613376.43518519,  944007.31182796,
        944007.31182796,  613376.43518519,  613376.43518519,
        944007.31182796,  613376.43518519,  944007.31182796,
        944007.31182796,  138407.5       ,  944007.31182796,
        944007.31182796, 2239583.33333333,  613376.43518519,
        138407.5       ,  312564.16666667,  138407.5       ,
        138407.5       ])

In [21]:
player_list = ['AB de Villiers','RG Sharma','MS Dhoni','AD Russell','CH Gayle', 'DA Warner', 'V Kohli', 'KD Karthik']

In [22]:
pd.set_option('display.max_rows', None)
df = pd.DataFrame({'Player':data.Player,'Actual': data.Salary, 'Predicted': y_pred_dt})
df['Actual'] = df['Actual'].astype(int)
df['Predicted'] = df['Predicted'].astype(int)
#display(df)
display(df[df.Player.isin(player_list)])

             Player   Actual  Predicted
3    AB de Villiers  1718750     944007
5        AD Russell  1328130     944007
35         CH Gayle   312500     944007
44        DA Warner  1953130    2148440
94       KD Karthik  1156250     944007
130        MS Dhoni  2343750    2148440
164       RG Sharma  2343750     944007
211         V Kohli  2656250    2239583

In [89]:
# Calculation of Mean Squared Error (MSE)
print("Mean squared error: %.2f" % mean_squared_error(data.Salary, y_pred_dt))

Mean squared error: 206240659846.13

In [88]:
print("Coefficient of determination: %.2f" % r2_score(data.Salary, y_pred_dt))

Coefficient of determination: 0.55

In [24]:
from sklearn import datasets, linear_model
from sklearn.metrics import mean_squared_error, r2_score

In [25]:
linear_regr = linear_model.LinearRegression()

In [26]:
linear_regr.fit(x,y)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [82]:
y_pred_ln = sc_y.inverse_transform(linear_regr.predict(x))

#y_pred_ln=np.reshape(np.array(y_pred_ln),(len(y_pred_ln),1))
#print(np.asarray(y_pred_ln))
#print(type(y_pred_ln))
#print(y_pred_ln.shape)
y_pred_ln=np.squeeze(y_pred_ln)
print(y_pred_ln.shape)

(67,)

In [83]:
#pd.set_option('display.max_rows', None)
df = pd.DataFrame({'Player':data.Player,'Actual': data.Salary, 'Predicted': y_pred_ln})
df['Actual'] = df['Actual'].astype(int)
df['Predicted'] = df['Predicted'].astype(int)
#display(df)
display(df[df.Player.isin(player_list)])

             Player   Actual  Predicted
3    AB de Villiers  1718750    1837209
5        AD Russell  1328130    1237471
35         CH Gayle   312500     764795
44        DA Warner  1953130    1077250
94       KD Karthik  1156250    1181689
130        MS Dhoni  2343750    1344428
164       RG Sharma  2343750     879970
211         V Kohli  2656250    1452799

In [84]:
print("Mean squared error: %.2f" % mean_squared_error(data.Salary, y_pred_ln))

Mean squared error: 321038733251.65

In [85]:
print("Coefficient of determination: %.2f" % r2_score(data.Salary, y_pred_ln))

Coefficient of determination: 0.31